### ISSUE TITLE
Finetune taiyi 报错：subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by rorepmezzz** [IDEA-CCNL/Fengshenbang-LM#208]
我用下面的方式安装了模型，然后调用/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.py来试图训练本地模型，出现了报错，不知道是否是需要进行额外的配置？

> !git clone https://github.com/IDEA-CCNL/Fengshenbang-LM.git
> %cd Fengshenbang-LM
> !git init
> !git clone https://github.com/IDEA-CCNL/fs_datasets.git fengshen/data/fs_datasets
> !pip install --editable .

报错信息：

Loading folder data from /workspace/train_data/part_0.
Done loading data. Len of images: 1031
--------warning no checkpoint found--------, remove args
/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:446: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.
  rank_zero_deprecation(
Loading DeepSpeed config from set PL_DEEPSPEED_CONFIG_PATH environment variable
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py:106: UserWarning: You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.
  rank_zero_warn("You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.")
initializing deepspeed distributed: GLOBAL_RANK: 0, MEMBER: 1/1
Missing logger folder: ../../workspace/taiyi-stablediffusion-1B/lightning_logs
calculate consumed samples: 0
Total steps: 10310
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Using ../../workspace/torch_extendsions as PyTorch extensions root...
Traceback (most recent call last):
  File "/workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.py", line 166, in <module>
    trainer.fit(model, datamoule, ckpt_path=args.load_ckpt_path)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1042, in _run
    self.strategy.setup(self)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 369, in setup
    self.init_deepspeed()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 480, in init_deepspeed
    self._initialize_deepspeed_train(model)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 513, in _initialize_deepspeed_train
    optimizer, lr_scheduler, _ = self._init_optimizers()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 486, in _init_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = _init_optimizers_and_lr_schedulers(self.lightning_module)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 180, in _init_optimizers_and_lr_schedulers
    optim_conf = model.trainer._call_lightning_module_hook("configure_optimizers", pl_module=model)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1305, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.py", line 56, in configure_optimizers
    return configure_optimizers(self, model_params=model_params)
  File "/workspace/Fengshenbang-LM/fengshen/models/model_utils.py", line 58, in configure_optimizers
    optimizer = FusedAdam(
  File "/opt/conda/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 73, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/opt/conda/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 403, in load
    return self.jit_load(verbose)
  File "/opt/conda/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 435, in jit_load
    op_module = load(
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1597, in _write_ninja_file_and_build_library
    get_compiler_abi_compatibility_and_version(compiler)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 336, in get_compiler_abi_compatibility_and_version
    if not check_compiler_ok_for_platform(compiler):
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 290, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/opt/conda/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.

**Comment by GGGGGGXY** [comment]
看起来貌似是没有c++编译器的样子，   可以看一下g++版本吗
