### ISSUE TITLE
unexpected keyword argument 'tokenizer_class'

### ISSUE THREAD

**Issue by itlubber** [IDEA-CCNL/Fengshenbang-LM#21]
```
Traceback (most recent call last):
  File "finetune.py", line 20, in <module>
    from model.roformer.modeling_roformer import RoFormerModel, RoFormerForMaskedLM, RoFormerForSequenceClassification
  File "model/roformer/modeling_roformer.py", line 894, in <module>
    class RoFormerModel(RoFormerPreTrainedModel):
  File "model/roformer/modeling_roformer.py", line 934, in RoFormerModel
    @add_code_sample_docstrings(
TypeError: add_code_sample_docstrings() got an unexpected keyword argument 'tokenizer_class'
```

[huggingface/transformers@f5af873](https://github.com/huggingface/transformers/commit/f5af87361718be29a1d3ddb2d8ef23f85b1c70c3)
replace **tokenizer_class** to **processor_class**

**Comment by suolyer** [comment]
这是transformers新版本的写法，transformer==4.9无此问题
