### ISSUE TITLE
cpu运行 Taiyi-Stable-Diffusion-1B-Chinese-v0.1 报错，能提供下环境配置吗？

### ISSUE THREAD

**Issue by smelly-dog** [IDEA-CCNL/Fengshenbang-LM#239]
报错信息如下
`Traceback (most recent call last):
  File "E:/Code/Text2Image/main.py", line 8, in <module>
    image = pipe(prompt).images[0]
  File "C:\Users\dell\anaconda3\envs\t2i\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\dell\anaconda3\envs\t2i\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 477, in __call__
    device = self._execution_device
  File "C:\Users\dell\anaconda3\envs\t2i\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 213, in _execution_device
    if self.device != torch.device("meta") or not hasattr(self.unet, "_hf_hook"):
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: meta
`

代码如图
![image](https://user-images.githubusercontent.com/32981640/208025282-b2a2c458-2751-415e-af53-2a266200305e.png)

环境信息如下
python: 3.7
pytorch: 1.8.1
diffusers: 0.10.2

**Comment by ganzhiruyi** [comment]
目前不支持cpu
