### ISSUE TITLE
执行examples/finetune_taiyi_stable_diffusion中finetune.py的时候提示Too many open files: '/tmp/tmp3t0d9_nc'

### ISSUE THREAD

**Issue by muximuxi** [IDEA-CCNL/Fengshenbang-LM#263]
感谢开源！请教一个问题：
在执行examples/finetune_taiyi_stable_diffusion中finetune.py的时候提示Too many open files: '/tmp/tmp3t0d9_nc'，请问是怎么回事呢？是完全按照示例中的进行的
具体错误信息如下：
--------warning no checkpoint found--------, remove args
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
The config attributes {'scaling_factor': 0.18215} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
load datasset txt ./demo_dataset/ len 6
Traceback (most recent call last):
  File "finetune.py", line 188, in <module>
  File "/home//lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
  File "/home//lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in _call_and_handle_interrupt
  File "/home//lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 78, in launch
  File "/home//lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
  File "/home//lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
  File "/home//lib/python3.8/multiprocessing/process.py", line 121, in start
  File "/home//lib/python3.8/multiprocessing/context.py", line 284, in _Popen
  File "/home//lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "/home//lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
  File "/home//lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
  File "/home//lib/python3.8/multiprocessing/reduction.py", line 60, in dump
  File "/home//lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 358, in reduce_storage
RuntimeError: unable to open shared memory object </torch_7809_846227385_1002> in read-write mode: Too many open files (24)
Traceback (most recent call last):
  File "/home//lib/python3.8/weakref.py", line 642, in _exitfunc
  File "/home//lib/python3.8/weakref.py", line 566, in __call__
  File "/home//lib/python3.8/tempfile.py", line 817, in _cleanup
  File "/home//lib/python3.8/tempfile.py", line 813, in _rmtree
  File "/home//lib/python3.8/shutil.py", line 714, in rmtree
  File "/home//lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmp3t0d9_nc'

**Comment by muximuxi** [comment]
在文件中添加以下：
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')
