### ISSUE TITLE
你们都是在Windows上跑的吗，我在Ubuntu上跑报错

### ISSUE THREAD

**Issue by sxk000** [IDEA-CCNL/Fengshenbang-LM#293]
感谢大佬分享！

尝试运行例子：Fengshenbang-LM/fengshen/examples/qa_t5/
运行：bash run_predict.sh
报错：run_predict.sh:行110: srun: 未找到命令

该怎么解决呢？

**Comment by sxk000** [comment]
直接跑：python finetune_t5_cmrc.py 
也报错：
Argument parse success.
superviseT5DataModel load start 2023-02-27 14:28:13
Traceback (most recent call last):
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 264, in hf_raise_for_status
    response.raise_for_status()
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1106, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1441, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 306, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-63fc4d7e-09c5cc4f6c72e6052a35f619)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Workspace/sxk/2023/Fengshenbang-LM/fengshen/examples/qa_t5/finetune_t5_cmrc.py", line 450, in <module>
    main()
  File "/home/Workspace/sxk/2023/Fengshenbang-LM/fengshen/examples/qa_t5/finetune_t5_cmrc.py", line 343, in main
    config = MT5Config.from_pretrained(args.pretrained_model_path)
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/transformers/configuration_utils.py", line 538, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/transformers/configuration_utils.py", line 565, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/transformers/configuration_utils.py", line 620, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/anaconda3/envs/s20230220e310fsb/lib/python3.10/site-packages/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by ganzhiruyi** [comment]
> 感谢大佬分享！
> 
> 尝试运行例子：Fengshenbang-LM/fengshen/examples/qa_t5/ 运行：bash run_predict.sh 报错：run_predict.sh:行110: srun: 未找到命令
> 
> 该怎么解决呢？

srun是在slurm下运行的命令，如果没有单卡运行可以直接python xxx.py，如果多卡可以torchrun

**Comment by dongluyang** [comment]
windows的安装，请参考 https://www.toutiao.com/article/7271252191200248360/

**Comment by dongluyang** [comment]
windows的安装，请参考 https://www.toutiao.com/article/7271252191200248360/
