### ISSUE TITLE
 python fengshen/examples/unimc/example.py 报错ModuleNotFoundError: Neither `tensorboard` nor `tensorboardX` is available. Try `pip install`ing either.

### ISSUE THREAD

**Issue by sxk000** [IDEA-CCNL/Fengshenbang-LM#297]
python fengshen/examples/unimc/example.py 
--------warning no checkpoint found--------, remove args
Traceback (most recent call last):
  File "/home/Workspace/sxk/2023/Fengshenbang-LM/fengshen/examples/unimc/example.py", line 82, in <module>
    main()
  File "/home/Workspace/sxk/2023/Fengshenbang-LM/fengshen/examples/unimc/example.py", line 18, in main
    model = UniMCPipelines(args, model_path=pretrained_model_path)
  File "/home/Workspace/sxk/2023/Fengshenbang-LM/fengshen/pipelines/multiplechoice.py", line 62, in __init__
    self.logger = loggers.TensorBoardLogger(save_dir=args.default_root_dir)
  File "/home/anaconda3/envs/s20230306e310fsb/lib/python3.10/site-packages/pytorch_lightning/loggers/tensorboard.py", line 110, in __init__
    super().__init__(
  File "/home/anaconda3/envs/s20230306e310fsb/lib/python3.10/site-packages/lightning_fabric/loggers/tensorboard.py", line 93, in __init__
    raise ModuleNotFoundError(
ModuleNotFoundError: Neither `tensorboard` nor `tensorboardX` is available. Try `pip install`ing either.

# 系统环境如下：
Environment
Linux version 3.10.0-693.el7.x86_64 ([builder@kbuilder.dev.centos.org](mailto:builder@kbuilder.dev.centos.org)) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) https://github.com/hpcaitech/ColossalAI/issues/1 SMP Tue Aug 22 21:09:27 UTC 2017

python=3.10.9

conda 4.14.0

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

# python第三方包环境：

aiohttp                  3.8.4
aiosignal                1.3.1
async-timeout            4.0.2
attrs                    22.2.0
certifi                  2022.12.7
charset-normalizer       3.1.0
datasets                 2.10.1
deepspeed                0.8.1
dill                     0.3.6
fengshen                 0.0.1      /home/Workspace/sxk/2023/Fengshenbang-LM
filelock                 3.9.0
frozenlist               1.3.3
fsspec                   2023.3.0
hjson                    3.1.0
huggingface-hub          0.12.1
idna                     3.4
jieba                    0.42.1
jieba-fast               0.53
lightning-utilities      0.7.1
multidict                6.0.4
multiprocess             0.70.14
ninja                    1.11.1
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.0
pandas                   1.5.3
pip                      22.3.1
psutil                   5.9.4
py-cpuinfo               9.0.0
pyarrow                  11.0.0
pydantic                 1.10.5
python-dateutil          2.8.2
pytorch-lightning        1.9.4
pytz                     2022.7.1
PyYAML                   6.0
regex                    2022.10.31
requests                 2.28.2
responses                0.18.0
setuptools               65.6.3
six                      1.16.0
tokenizers               0.13.2
torch                    1.13.1
torchmetrics             0.11.3
tqdm                     4.65.0
transformers             4.26.1
typing_extensions        4.5.0
urllib3                  1.26.14
wheel                    0.38.4
xxhash                   3.2.0
yarl                     1.8.2

**Comment by sxk000** [comment]
解决方法：pip install tensorboard
