### ISSUE TITLE
ImportError: workspace/torch_extendsions/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zhenzi0322** [IDEA-CCNL/Fengshenbang-LM#303]
https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/finetune_taiyi_stable_diffusion

```
./finetune.sh
```

error
```
Traceback (most recent call last):
  File "/mnt/data/long/finetune_taiyi_stable_diffusion/finetune.py", line 210, in <module>
    trainer.fit(model, datamoule, ckpt_path=args.load_ckpt_path)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1147, in _run
    self.strategy.setup(self)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 376, in setup
    self.init_deepspeed()
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 490, in init_deepspeed
    self._initialize_deepspeed_train(model)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 523, in _initialize_deepspeed_train
    optimizer, lr_scheduler, _ = self._init_optimizers()
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 496, in _init_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = _init_optimizers_and_lr_schedulers(self.lightning_module)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 179, in _init_optimizers_and_lr_schedulers
    optim_conf = model.trainer._call_lightning_module_hook("configure_optimizers", pl_module=model)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/mnt/data/long/finetune_taiyi_stable_diffusion/finetune.py", line 125, in configure_optimizers
    return configure_optimizers(self)
  File "/mnt/data/long/finetune_taiyi_stable_diffusion/fengshen/models/model_utils.py", line 69, in configure_optimizers
    optimizer = FusedAdam(
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 73, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
    return self.jit_load(verbose)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 520, in jit_load
    op_module = load(
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: workspace/torch_extendsions/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory
```

**Comment by GGGGGGXY** [comment]
pip install deepspeed

**Comment by zhenzi0322** [comment]
> pip install deepspeed

装过了，但是编译不了呀，您们装的是什么版本的？

**Comment by GGGGGGXY** [comment]
> > pip install deepspeed
> 
> 装过了，但是编译不了呀，您们装的是什么版本的？

最新版的，   可以上deepspeed的项目问一下

**Comment by zhenzi0322** [comment]
好的

**Comment by zhenzi0322** [comment]
我发现不是`deepspeed`项目的问题，而是`ninja -v`的问题。

我在采用`ninja -v`时出现如下：

![image](https://user-images.githubusercontent.com/34839719/224596758-055464cd-c6bc-4ee3-8508-8f98d462c1e8.png)
