### ISSUE TITLE
LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”

### ISSUE THREAD

**Issue by candowu** [IDEA-CCNL/Fengshenbang-LM#309]
pip install -e . failed

 Using cached https://mirrors.aliyun.com/pypi/packages/0f/c0/9b57e9ec56f6f405726a384b109f8da1267e41feea081850c2fce1735712/deepspeed-0.8.3.tar.gz (765 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\candowu\AppData\Local\Temp\pip-install-zgtokznx\deepspeed_5b2d035f5a4c4576bd710073312fe09b\setup.py", line 156, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\candowu\AppData\Local\Temp\pip-install-zgtokznx\deepspeed_5b2d035f5a4c4576bd710073312fe09b\setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mjw3177109** [comment]
I also have this problem

**Comment by John-jin** [comment]
me too

**Comment by DddJLin** [comment]
me three

**Comment by hahahonline** [comment]
someone fixed?

**Comment by GGGGGGXY** [comment]
are you installing in windows？

**Comment by DddJLin** [comment]
Yes!

GAOXinyu ***@***.***>于2023年5月22日 周一22:00写道：

**Comment by dongluyang** [comment]
please refer to this link https://www.toutiao.com/article/7271252191200248360/, i give a solution for resolving above problem in windows

**Comment by CCodeInspect** [comment]
> pip install -e . failed
> 
> Using cached https://mirrors.aliyun.com/pypi/packages/0f/c0/9b57e9ec56f6f405726a384b109f8da1267e41feea081850c2fce1735712/deepspeed-0.8.3.tar.gz (765 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [16 lines of output] test.c LINK : fatal error LNK1181: 无法打开输入文件“aio.lib” Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\Users\candowu\AppData\Local\Temp\pip-install-zgtokznx\deepspeed_5b2d035f5a4c4576bd710073312fe09b\setup.py", line 156, in abort(f"Unable to pre-compile {op_name}") File "C:\Users\candowu\AppData\Local\Temp\pip-install-zgtokznx\deepspeed_5b2d035f5a4c4576bd710073312fe09b\setup.py", line 48, in abort assert False, msg AssertionError: Unable to pre-compile async_io [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2) DS_BUILD_OPS=1 [WARNING] async_io requires the dev libaio .so object and headers but these were not found. [WARNING] If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found. [WARNING] One can disable async_io with DS_BUILD_AIO=0 [ERROR] Unable to pre-compile async_io [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

i also meet it 
![1701493705794](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/44918169/846642ab-86ce-4f81-8721-281dcb184e01)

**Comment by llaichiyu** [comment]
> please refer to this link https://www.toutiao.com/article/7271252191200248360/, i give a solution for resolving above problem in windows

**i clone Deepspeed and use python setup.py bdist_wheel ,then give me the errors:**
![1701494378521](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/44918169/7a77952a-7075-43a8-80bc-e1829e197a5e)

**Comment by CCodeInspect** [comment]
> please refer to this link https://www.toutiao.com/article/7271252191200248360/, i give a solution for resolving above problem in windows

> please refer to this link https://www.toutiao.com/article/7271252191200248360/, i give a solution for resolving above problem in windows

**i clone Deepspeed and use python setup.py bdist_wheel ,then give me the errors:**
![1701494378521](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/44918169/7a77952a-7075-43a8-80bc-e1829e197a5e)

**Comment by CCodeInspect** [comment]
> please refer to this link https://www.toutiao.com/article/7271252191200248360/, i give a solution for resolving above problem in windows

**And i search a answer about how to solve :https://github.com/microsoft/DeepSpeed/issues/1769.
And the issues advice me to use wsl, i wonder to know your steps about how to solve.Thanks dalao ~**

**Comment by fengzhi09** [comment]
> > please refer to this link https://www.toutiao.com/article/7271252191200248360/, i give a solution for resolving above problem in windows
> 
> > please refer to this link https://www.toutiao.com/article/7271252191200248360/, i give a solution for resolving above problem in windows
> 
> **i clone Deepspeed and use python setup.py bdist_wheel ,then give me the errors:** ![1701494378521](https://private-user-images.githubusercontent.com/44918169/287422815-7a77952a-7075-43a8-80bc-e1829e197a5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzYyNjQsIm5iZiI6MTcwNDE3NTk2NCwicGF0aCI6Ii80NDkxODE2OS8yODc0MjI4MTUtN2E3Nzk1MmEtNzA3NS00M2E4LTgwYmMtZTE4MjllMTk3YTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA2MTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZDQxOGQ2ZjNkOTdhMjE5NmZlYWU3MDE0ZGI2MjJlYjU2MzNlYTcyODk1NGQ1Y2M2NTZiM2FkZjEwNWU5ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7_2T8NXA9iFoBMFLO6ylof1mb563KQQ6MT_OJfwzxQg)
I met the problem before, after i run `pip install libaio` i got bellow err 
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/22229659/431aea06-e4a4-450c-9848-c98caacdabca)
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/22229659/26cdf726-02d8-4d1b-ace2-133dfd29c94d)

**Comment by xiaofanku** [comment]
这个项目是不是不支持window呀?
```
(Fengshenbang-LM) PS D:\Fengshenbang-LM> python .\demo.py
[2025-04-09 22:11:15,729] [WARNING] [real_accelerator.py:194:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2025-04-09 22:11:15,735] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cpu (auto detect)
test.c
LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
W0409 22:11:18.100000 26044 Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "D:\Fengshenbang-LM\demo.py", line 2, in <module>
    from fengshen import UbertPiplines
ImportError: cannot import name 'UbertPiplines' from 'fengshen' (D:\Fengshenbang-LM\fengshen\__init__.py)
```
