### ISSUE TITLE
使用提供的镜像环境对longformer进行finetune，报错

### ISSUE THREAD

**Issue by vikotse** [IDEA-CCNL/Fengshenbang-LM#324]
1. 在自己的docker镜像环境下根据fengshen/examples/classification/finetune_classification.sh修改，对longformer进行finetune，报错。
2. 于是，使用提供的fengshenbang/pytorch:1.10-cuda11.1-cudann8-devel这个镜像执行finetune脚本，还是会报相同错误。

执行打印结果如下：

Global seed set to 42
IDEA-CCNL/Erlangshen-Longformer-110M
Traceback (most recent call last):
  File "/repo/Fengshenbang-LM/finetune_longformer.py", line 389, in <module>
    main()
  File "/repo/Fengshenbang-LM/finetune_longformer.py", line 368, in main
    checkpoint_callback = TaskModelCheckpoint(args).callbacks
  File "/repo/Fengshenbang-LM/finetune_longformer.py", line 317, in __init__
    self.callbacks = ModelCheckpoint(monitor=args.monitor,
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 245, in __init__
    self.__validate_init_configuration()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 420, in __validate_init_configuration
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: Combination of parameters every_n_train_steps=100.0, every_n_epochs=1 and train_time_interval=None should be mutually exclusive.

注：
对finetune_classification.sh修改的部分仅包含MODEL_TYPE、PRETRAINED_MODEL_PATH、以及相关数据路径，具体如下：
![image](https://user-images.githubusercontent.com/5728396/233378229-ef2953f1-582c-4e47-8ead-37a28f9f3dde.png)

**Comment by GGGGGGXY** [comment]
看起来是lightning的checkpoint的检测到一些不合理的配置，我一般适用的lightning版本是1.7.6，可以贴一下你的版本我看下是不是lightning版本导致的兼容问题

**Comment by GGGGGGXY** [comment]
every_n_epochs 跟 every_n_train_steps 不能同时设置

**Comment by vikotse** [comment]
> 看起来是lightning的checkpoint的检测到一些不合理的配置，我一般适用的lightning版本是1.7.6，可以贴一下你的版本我看下是不是lightning版本导致的兼容问题

![image](https://user-images.githubusercontent.com/5728396/233556704-57d8eecf-9d67-4de9-8eb7-84b31d5aa2bc.png)
用的就是提供的镜像中的lightning，1.7.6版本，finetune脚本也没有作改动

**Comment by GGGGGGXY** [comment]
> > 看起来是lightning的checkpoint的检测到一些不合理的配置，我一般适用的lightning版本是1.7.6，可以贴一下你的版本我看下是不是lightning版本导致的兼容问题
> 
> ![image](https://user-images.githubusercontent.com/5728396/233556704-57d8eecf-9d67-4de9-8eb7-84b31d5aa2bc.png) 用的就是提供的镜像中的lightning，1.7.6版本，finetune脚本也没有作改动

相关同学写代码可能不规划，可以参考我的这个checkpoint这里的add_parse，这几个参数
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/15215819/233557042-c9559f2d-e2d6-43ef-9c66-4517202a95bb.png">
比如every_n_train_steps设置了就不要设置every_n_epochs， 需要设置为None

**Comment by vikotse** [comment]
> > > 看起来是lightning的checkpoint的检测到一些不合理的配置，我一般适用的lightning版本是1.7.6，可以贴一下你的版本我看下是不是lightning版本导致的兼容问题
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/5728396/233556704-57d8eecf-9d67-4de9-8eb7-84b31d5aa2bc.png) 用的就是提供的镜像中的lightning，1.7.6版本，finetune脚本也没有作改动
> 
> 相关同学写代码可能不规划，可以参考我的这个checkpoint这里的add_parse，这几个参数 <img alt="image" width="1329" src="https://user-images.githubusercontent.com/15215819/233557042-c9559f2d-e2d6-43ef-9c66-4517202a95bb.png"> 比如every_n_train_steps设置了就不要设置every_n_epochs， 需要设置为None

https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.py#L323
找到问题了，这行every_n_epochs=1改为every_n_epochs=args.every_n_epochs
并且在add_argparse_args()中加上parser.add_argument('--every_n_epochs', default=None, type=int)，即符合预期

**Comment by vikotse** [comment]
@GGGGGGXY lightning这个问题解决，另外还有新问题：

98.0 M    Trainable params
0         Non-trainable params
98.0 M    Total params
392.039   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:236: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Sanity Checking DataLoader 0:   0%|                                                         | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/repo/Fengshenbang-LM/finetune_longformer.py", line 391, in <module>
    main()
  File "/repo/Fengshenbang-LM/finetune_longformer.py", line 384, in main
    trainer.fit(model, data_model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
    val_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/repo/Fengshenbang-LM/finetune_longformer.py", line 282, in validation_step
    output = self.model(**batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'labels'
