### ISSUE TITLE
finetune_classification.sh脚本对longformer进行finetune，报错

### ISSUE THREAD

**Issue by vikotse** [IDEA-CCNL/Fengshenbang-LM#325]
https://github.com/IDEA-CCNL/Fengshenbang-LM/issues/324
在采用上述issue中的方式，解决完[finetune_classification.py](https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.py)中的argument问题后。

发现后续出现更多的问题，目前查询了一些相关信息后，发现finetune_classification.py似乎并不能直接跑通longformer的finetune，目前也没有提供其他的longformer finetune示例，是否可以帮忙看下其中的问题？

![image](https://user-images.githubusercontent.com/5728396/233819050-977be8b8-bfc5-439f-a1be-8687fe425b60.png)

数据这块用的是CLUE的tnews数据集，与示例脚本一致
https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.sh

执行后报错

98.0 M Trainable params
0 Non-trainable params
98.0 M Total params
392.039 Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:236: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the num_workers argument(try 10 which is the number of cpus on this machine) in theDataLoader` init to improve performance.
rank_zero_warn(
Sanity Checking DataLoader 0: 0%| | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
File "/repo/Fengshenbang-LM/finetune_longformer.py", line 391, in
main()
File "/repo/Fengshenbang-LM/finetune_longformer.py", line 384, in main
trainer.fit(model, data_model)
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
self._call_and_handle_interrupt(
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
return trainer_fn(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
results = self._run(model, ckpt_path=self.ckpt_path)
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
results = self._run_stage()
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
return self._run_train()
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
self._run_sanity_check()
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
val_loop.run()
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
self.advance(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
self.advance(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
output = self._evaluation_step(**kwargs)
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
output = fn(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
return self.model.validation_step(*args, **kwargs)
File "/repo/Fengshenbang-LM/finetune_longformer.py", line 282, in validation_step
output = self.model(**batch)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'labels'

**Comment by suolyer** [comment]
这个错误主要是模型没有加载正确导致的，你可以将 line48的```'fengshen-longformer': LongformerModel```改为```'fengshen-longformer': LongformerForSequenceClassification```

**Comment by vikotse** [comment]
> 这个错误主要是模型没有加载正确导致的，你可以将 line48的`'fengshen-longformer': LongformerModel`改为`'fengshen-longformer': LongformerForSequenceClassification`

嗯嗯，已经改为LongformerForSequenceClassification，但仍存在不少问题，还在解决当中；

**Comment by vikotse** [comment]
共有以下几个地方需要fix，修改后调通训练流程：
1. finetune longformer使用的模型类应改为LongformerForSequenceClassification，LongformerModel本身没有classification的部分，只有pretrain的backbone。
具体解决方法：把[finetune_classification.py: 48行](https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.py#L48)的LongformerModel改为LongformerForSequenceClassification；19行import中，加上LongformerForSequenceClassification

2. LitModel __init__函数中，from_pretrained应加上num_labels参数，否则在from_pretrained加载预训练模型后，调用初始化__init__函数时，从pretrained model config中获取不到num_labels，导致默认为2了（参考PretrainedConfig中num_labels参数初始化[configuration_utils.py: 331行](https://github.com/huggingface/transformers/blob/main/src/transformers/configuration_utils.py#L331)）。
具体解决方法：在[finetune_classification.py: 244~245行](https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.py#L245)from_pretrained参数中，加上num_labels
`self.model = model_dict[args.model_type].from_pretrained(args.pretrained_model_path, num_labels=args.num_labels)`

3. LitModel中training_step、validation_step中，output并不是list，而是特定的返回类型，
具体解决方法：把[finetune_classification.py: 266行、283行](https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.py#L266)的loss, logits = output[0], output[1]，改为
`
loss = output.loss
logits = output.logits
`

**Comment by feng-1985** [comment]
神奇，训了几个epoch，居然不收敛！配置同上，为啥呢？ 请教一下 @vikotse
