### ISSUE TITLE
使用微调finetune_taiyi_stable_diffusion/finetune.py出现的bug信息

### ISSUE THREAD

**Issue by TTyb** [IDEA-CCNL/Fengshenbang-LM#412]
从`https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1`和`https://github.com/IDEA-CCNL/Fengshenbang-LM`clone下来后：

```
git-lfs clone https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1
git clone https://github.com/IDEA-CCNL/Fengshenbang-LM
```

进入文件夹调试：
```
cd /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion
```

由于路径下没有ckpt需要新建：
```
mkdir ckpt
cp /workspace/Taiyi-Stable-Diffusion-1B-Chinese-v0.1/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.ckpt ./
```

执行命令：

```
python finetune.py --model_path /workspace/Taiyi-Stable-Diffusion-1B-Chinese-v0.1 --datasets_path /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/demo_dataset/ --datasets_type txt --train_batchsize 1 --load_ckpt_path /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/ckpt/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.ckpt
```

出现第一次报错：

```
root@f87a849f30d3:/workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion# python finetune.py --model_path /workspace/Taiyi-Stable-Diffusion-1B-Chinese-v0.1 --datasets_path /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/demo_dataset/ --datasets_type txt --train_batchsize 1 --load_ckpt_path /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/ckpt/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.ckpt
-----------args is: 
 {'learning_rate': 5e-05, 'min_learning_rate': 1e-07, 'lr_decay_steps': 0, 'lr_decay_ratio': 1.0, 'warmup_steps': 0, 'warmup_ratio': 0.1, 'weight_decay': 0.1, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'adam_epsilon': 1e-08, 'model_path': '/workspace/Taiyi-Stable-Diffusion-1B-Chinese-v0.1', 'scheduler_type': 'polynomial', 'datasets_path': ['/workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/demo_dataset/'], 'datasets_type': ['txt'], 'resolution': 512, 'center_crop': False, 'thres': 0.2, 'num_workers': 8, 'dataloader_workers': 2, 'train_batchsize': 1, 'val_batchsize': 16, 'test_batchsize': 16, 'datasets_name': None, 'train_datasets_field': 'train', 'val_datasets_field': 'validation', 'test_datasets_field': 'test', 'train_file': None, 'val_file': None, 'test_file': None, 'raw_file_type': 'json', 'sampler_type': 'random', 'use_mpu': False, 'logger': True, 'enable_checkpointing': True, 'default_root_dir': None, 'gradient_clip_val': None, 'gradient_clip_algorithm': None, 'num_nodes': 1, 'num_processes': None, 'devices': None, 'gpus': None, 'auto_select_gpus': False, 'tpu_cores': None, 'ipus': None, 'enable_progress_bar': True, 'overfit_batches': 0.0, 'track_grad_norm': -1, 'check_val_every_n_epoch': 1, 'fast_dev_run': False, 'accumulate_grad_batches': None, 'max_epochs': None, 'min_epochs': None, 'max_steps': -1, 'min_steps': None, 'max_time': None, 'limit_train_batches': None, 'limit_val_batches': None, 'limit_test_batches': None, 'limit_predict_batches': None, 'val_check_interval': None, 'log_every_n_steps': 50, 'accelerator': None, 'strategy': None, 'sync_batchnorm': False, 'precision': 32, 'enable_model_summary': True, 'weights_save_path': None, 'num_sanity_val_steps': 2, 'resume_from_checkpoint': None, 'profiler': None, 'benchmark': None, 'deterministic': None, 'reload_dataloaders_every_n_epochs': 0, 'auto_lr_find': False, 'replace_sampler_ddp': True, 'detect_anomaly': False, 'auto_scale_batch_size': False, 'plugins': None, 'amp_backend': 'native', 'amp_level': None, 'move_metrics_to_cpu': False, 'multiple_trainloader_mode': 'max_size_cycle', 'freeze_unet': False, 'text_model_path': None, 'freeze_text_encoder': False, 'use_local_token': False, 'use_local_unet': False, 'monitor': 'step', 'mode': 'max', 'save_ckpt_path': './ckpt/', 'load_ckpt_path': '/workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/ckpt/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.ckpt', 'filename': 'model-ep{epoch:02d}-st{step:d}', 'save_last': False, 'save_top_k': 10, 'every_n_train_steps': None, 'save_weights_only': False, 'every_n_epochs': None, 'save_on_train_epoch_end': None}
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1764: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.
  rank_zero_warn(
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.68it/s]
load datasset txt /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/demo_dataset/ len 6
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py:89: PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
  rank_zero_warn(
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:105: UserWarning: You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.
  rank_zero_warn("You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.")
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:616: UserWarning: Checkpoint directory /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/ckpt exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
Total steps: 6000
Restoring states from the checkpoint path at /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/ckpt/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.ckpt
Traceback (most recent call last):
  File "finetune.py", line 200, in <module>
    trainer.fit(model, datamoule, ckpt_path=args.load_ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1110, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1065, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 174, in restore_model
    self.trainer._call_lightning_module_hook("on_load_checkpoint", self._loaded_checkpoint)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "finetune.py", line 165, in on_load_checkpoint
    global_step_offset = checkpoint["global_step"]
KeyError: 'global_step'
```

修改代码：

```
vim finetune.py
# global_step_offset = checkpoint["global_step"]
if 'global_step' in checkpoint:
	global_step_offset = checkpoint["global_step"]
else:
	global_step_offset = None
```

重新运行出现报错：

```
root@f87a849f30d3:/workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion# python finetune.py --model_path /workspace/Taiyi-Stable-Diffusion-1B-Chinese-v0.1 --datasets_path /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/demo_dataset/ --datasets_type txt --train_batchsize 1 --load_ckpt_path /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/ckpt/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.ckpt
...
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1764: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.
  rank_zero_warn(
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.48it/s]
load datasset txt /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/demo_dataset/ len 6
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py:89: PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
  rank_zero_warn(
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:105: UserWarning: You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.
  rank_zero_warn("You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.")
/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:616: UserWarning: Checkpoint directory /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/ckpt exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
Total steps: 6000
Restoring states from the checkpoint path at /workspace/Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/ckpt/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.ckpt
Traceback (most recent call last):
  File "finetune.py", line 200, in <module>
    trainer.fit(model, datamoule, ckpt_path=args.load_ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1110, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1065, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 182, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 343, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for StableDiffusion:
	Missing key(s) in state_dict: "text_encoder.embeddings.word_embeddings.weight", "text_encoder.embeddings.position_embeddings.weight", ............"unet.conv_out.bias". 
	Unexpected key(s) in state_dict: "model.diffusion_model.input_blocks.0.0.weight", "model.diffusion_model.input_blocks.0.0.bias",........
```

查询`finetune_taiyi_stable_diffusion_example.ipynb`和`finetune.py`区别，区别在于最后一句：

```
trainer.fit(model, datamoule) # finetune_taiyi_stable_diffusion_example.ipynb
trainer.fit(model, datamoule, ckpt_path=args.load_ckpt_path) # finetune.py
```

所以删掉`ckpt_path=args.load_ckpt_path`，重新跑得到错误：

```
Traceback (most recent call last):
  File "finetune.py", line 201, in <module>
    trainer.fit(model, datamoule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 87, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 201, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 248, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 358, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1705, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 216, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 153, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/optimization.py", line 439, in step
    loss = closure()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 138, in _wrap_closure
    closure_result = closure()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 141, in closure
    self._backward_fn(step_output.closure_loss)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 304, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 191, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, optimizer, optimizer_idx, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 80, in backward
    model.backward(closure_loss, optimizer, optimizer_idx, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1450, in backward
    loss.backward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

```

自此终结无法优化，该项目git上的代码可能作者重新校验一下

**Comment by wxj630** [comment]
你什么都不要改，args.model_path传进去clone下来的
https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1，然后直接跑finetune.sh

**Comment by luvWY** [comment]
> 你什么都不要改，args.model_path传进去clone下来的 [https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1，然后直接跑finetune.sh](https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1%EF%BC%8C%E7%84%B6%E5%90%8E%E7%9B%B4%E6%8E%A5%E8%B7%91finetune.sh)

我能问下您finetune的过程中 loss下降明显吗 我感觉我的都不动弹
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/17444143/8e09b3bc-0c5d-46cc-865d-3f15a34d7105)

**Comment by wxj630** [comment]
diffusion model的finetune的训练loss确实是不怎么下降的，这是正常的，你可以测试下文生图效果

**Comment by luvWY** [comment]
> 

如果从loss训练来看不明显，我如何评价我微调后的数据集优于pretrain呀。随机写一点prompt去对比，好像不太全面

**Comment by luvWY** [comment]
我想咨询下，一般clip打分来评测。是依赖当前使用的text-encorder对应的clip模型，还是可以采用三方的clip模型。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDEA-CCNL/Fengshenbang-LM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDEA-CCNL/Fengshenbang-LM] 使用微调finetune_taiyi_stable_diffusion/finetune.py出现的bug信息 (Issue #412)





 
diffusion model的finetune的训练loss确实是不怎么下降的，这是正常的，你可以测试下文生图效果
