### ISSUE TITLE
fintuning摘要任务时报错 No module named 'utils'

### ISSUE THREAD

**Issue by aidejieceng** [IDEA-CCNL/Fengshenbang-LM#98]
(summaryfengshen) [hyzhang10@083207 fengshen_pegasus]$ sh randeng_pegasus_523M_summary.sh 
Building prefix dict from the default dictionary ...
Loading model from cache /data/hyzhang10/environment/jiebaCache/jieba.cache
Loading model cost 0.662 seconds.
Prefix dict has been built successfully.
Using custom data configuration default-d0a497e7c2f7c312
Reusing dataset json (/data/hyzhang10/.cache/huggingface/datasets/json/default-d0a497e7c2f7c312/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)
Using custom data configuration default-7e746462023f1ebc
Reusing dataset json (/data/hyzhang10/.cache/huggingface/datasets/json/default-7e746462023f1ebc/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)
Using custom data configuration default-33b0ce470df9653c
Reusing dataset json (/data/hyzhang10/.cache/huggingface/datasets/json/default-33b0ce470df9653c/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
initializing deepspeed distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[2022-08-04 14:51:48,391] [WARNING] [deepspeed.py:629:_auto_select_batch_size] Tried to infer the batch size for internal deepspeed logging from the `train_dataloader()`. To ensure DeepSpeed logging remains correct, please manually pass the plugin with the batch size, `Trainer(strategy=DeepSpeedPlugin(logging_batch_size_per_gpu=batch_size))`.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
You have not specified an optimizer or scheduler within the DeepSpeed config. Using `configure_optimizers` to define optimizer and scheduler.
/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py:37: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
[2022-08-04 14:51:54,431] [WARNING] [engine.py:1126:_configure_optimizer] **** You are using ZeRO with an untested optimizer, proceed with caution *****
Using /data/hyzhang10/.cache/torch_extensions as PyTorch extensions root...
/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/torch/utils/cpp_extension.py:311: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 5.0 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 5 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Emitting ninja build file /data/hyzhang10/.cache/torch_extensions/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
Loading extension module utils...
Traceback (most recent call last):
  File "finetune_pegasus_summary.py", line 330, in <module>
    main()
  File "finetune_pegasus_summary.py", line 320, in main
    trainer.fit(model, data_model)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1188, in _run
    self._pre_dispatch()
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1223, in _pre_dispatch
    self.accelerator.pre_dispatch(self)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 136, in pre_dispatch
    self.training_type_plugin.pre_dispatch()
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 389, in pre_dispatch
    self.init_deepspeed()
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 459, in init_deepspeed
    self._initialize_deepspeed_train(model)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 492, in _initialize_deepspeed_train
    model, deepspeed_optimizer = self._setup_model_and_optimizer(model, optimizer, scheduler)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/deepspeed.py", line 423, in _setup_model_and_optimizer
    deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/deepspeed/__init__.py", line 119, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 291, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1129, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1350, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 141, in __init__
    util_ops = UtilsBuilder().load()
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 403, in load
    return self.jit_load(verbose)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 435, in jit_load
    op_module = load(
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1317, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1699, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'utils'

**Comment by GGGGGGXY** [comment]
这里的错误主要是ImportError: No module named 'utils' 没有找到utils这个包导致的，实际上这个包是动态编译的，
<img width="408" alt="image" src="https://user-images.githubusercontent.com/15215819/182819896-d8b84c14-4616-4adc-b6a8-aaca631ca666.png">
<img width="408" alt="image" src="https://user-images.githubusercontent.com/15215819/182820090-276f99a7-0f73-465f-98d6-963752e3a626.png">
看你的报错应该是gcc版本过低
<img width="828" alt="image" src="https://user-images.githubusercontent.com/15215819/182820162-ec8e4fd2-8c34-4822-9a80-b526ce2a7602.png">
可以尝试关闭deepspeed或者升级gcc版本后再试试

**Comment by aidejieceng** [comment]
关闭deepspeed后，目前能正常训练，但训练过程不收敛，模型loss一直在5.0附近，并未下降，训练指标未改变。
训练命令为：
python finetune_pegasus_summary.py \
    --max_epochs 10 \
    --gpus 1 \
    --num_nodes 1 \
    --default_root_dir /data/hyzhang10/research/summary_research/fengshen_pegasus \
    --dirpath /data/hyzhang10/research/summary_research/fengshen_pegasus/ckpt  \
    --save_top_k 5 \
    --monitor val_loss  \
    --mode min  \
    --save_last  \
    --every_n_train_steps 5000  \
    --val_check_interval 0.1  \
    --pretrained_model_path /data/hyzhang10/research/summary_research/fengshen_pegasus/PretrainedModel/Randeng-Pegasus-523M-Chinese \
    --output_save_path /data/hyzhang10/research/summary_research/fengshen_pegasus/pegasus_model_outpus/Randeng-Pegasus-523M-Chinese.json \
    --datasets_name lcsts  \
    --num_workers 30  \
    --train_batchsize 32 \
    --val_batchsize 32 \
    --test_batchsize 32 \
    --max_seq_length 128  \
    --max_dec_length 64  \
-------------------------------------------------------------------
以下为运行日志：
(summaryfengshen) [hyzhang10@083207 fengshen_pegasus]$ sh randeng_pegasus_523M_summary.sh 
Building prefix dict from the default dictionary ...
Loading model from cache /data/hyzhang10/environment/jiebaCache/jieba.cache
Loading model cost 0.708 seconds.
Prefix dict has been built successfully.
Namespace(accelerator=None, accumulate_grad_batches=None, amp_backend='native', amp_level=None, auto_lr_find=False, auto_scale_batch_size=False, auto_select_gpus=False, benchmark=False, check_val_every_n_epoch=1, checkpoint_callback=None, datasets_name='lcsts', default_root_dir='/data/hyzhang10/research/summary_research/fengshen_pegasus', detect_anomaly=False, deterministic=False, devices=None, dirpath='/data/hyzhang10/research/summary_research/fengshen_pegasus/ckpt', do_eval_only=False, enable_checkpointing=True, enable_model_summary=True, enable_progress_bar=True, every_n_epochs=0, every_n_train_steps=5000.0, fast_dev_run=False, filename='model-{epoch:02d}-{train_loss:.4f}', flush_logs_every_n_steps=None, gpus=1, gradient_clip_algorithm=None, gradient_clip_val=None, ipus=None, learning_rate=5e-06, limit_predict_batches=1.0, limit_test_batches=1.0, limit_train_batches=1.0, limit_val_batches=1.0, log_every_n_steps=50, log_gpu_memory=None, logger=True, max_dec_length=64, max_epochs=10, max_seq_length=128, max_steps=-1, max_time=None, min_epochs=None, min_steps=None, mode='min', monitor='val_loss', move_metrics_to_cpu=False, multiple_trainloader_mode='max_size_cycle', not_save_on_train_epoch_end=False, num_nodes=1, num_processes=1, num_sanity_val_steps=2, num_workers=30, output_save_path='/data/hyzhang10/research/summary_research/fengshen_pegasus/pegasus_model_outpus/Randeng-Pegasus-523M-Chinese.json', overfit_batches=0.0, plugins=None, precision=32, prepare_data_per_node=None, pretrained_model_path='/data/hyzhang10/research/summary_research/fengshen_pegasus/PretrainedModel/Randeng-Pegasus-523M-Chinese', process_position=0, profiler=None, progress_bar_refresh_rate=None, reload_dataloaders_every_epoch=False, reload_dataloaders_every_n_epochs=0, replace_sampler_ddp=True, resume_from_checkpoint=None, rouge_keys='rouge1,rouge2,rougeL', save_last=True, save_top_k=5.0, save_weights_only=False, stochastic_weight_avg=False, strategy=None, sync_batchnorm=False, terminate_on_nan=None, test_batchsize=32, test_datasets_field='test', tpu_cores=None, track_grad_norm=-1, train_batchsize=32, train_datasets_field='train', val_batchsize=32, val_check_interval=0.1, val_datasets_field='val', warmup=0.01, weight_decay=0.1, weights_save_path=None, weights_summary='top')
-----------------------------
Using custom data configuration default-2d14b688facbfb6b
Reusing dataset json (/data/hyzhang10/.cache/huggingface/datasets/json/default-2d14b688facbfb6b/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)
Using custom data configuration default-12dcee9d16eaa19f
Reusing dataset json (/data/hyzhang10/.cache/huggingface/datasets/json/default-12dcee9d16eaa19f/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)
Using custom data configuration default-3957e7c4af6a9455
Reusing dataset json (/data/hyzhang10/.cache/huggingface/datasets/json/default-3957e7c4af6a9455/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]
/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py:37: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(

  | Name         | Type                            | Params
-----------------------------------------------------------------
0 | model        | PegasusForConditionalGeneration | 523 M 
1 | rouge_metric | ROUGEScore                      | 0     
-----------------------------------------------------------------
521 M     Trainable params
2.1 M     Non-trainable params
523 M     Total params
2,094.350 Total estimated model params size (MB)
Validation sanity check:   0%|                                                                                                                                                              | 0/2 [00:00<?, ?it/s]rm /data/hyzhang10/research/summary_research/fengshen_pegasus/pegasus_model_outpus/Randeng-Pegasus-523M-Chinese_0.json
/data/hyzhang10/environment/miniconda3/envs/summaryfengshen/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:59: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 32. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
Validation sanity check: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:15<00:00,  7.27s/it]rouge:
 {'rouge1_fmeasure': tensor(0.2330), 'rouge1_precision': tensor(0.1731), 'rouge1_recall': tensor(0.3905), 'rouge2_fmeasure': tensor(0.1201), 'rouge2_precision': tensor(0.0887), 'rouge2_recall': tensor(0.2038), 'rougeL_fmeasure': tensor(0.1951), 'rougeL_precision': tensor(0.1449), 'rougeL_recall': tensor(0.3274)}
Epoch 0:   0%|▍                                                                                                                                        | 158/49302 [02:34<13:20:15,  1.02it/s, *loss=5.18*, v_num=6]

**Comment by ganzhiruyi** [comment]
There is a bug when turn off deepspeed config, refer to
https://github.com/IDEA-CCNL/Fengshenbang-LM/pull/101
